on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest

    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ğŸ Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: ğŸƒ Run python script
      run: |
        python build.py
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.ssrsm.mk
        username: auto-deploy@ssrsm.mk
        password: ${{ secrets.ftp_password }}
        local-dir: ./build/
